# Generated by Django 4.2.5 on 2023-09-27 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MeterPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpan', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('flow_filename', models.CharField(max_length=100)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.meter')),
            ],
        ),
        migrations.AddField(
            model_name='meter',
            name='meter_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.meterpoint'),
        ),
    ]
