# Generated by Django 4.2.5 on 2023-10-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_meterpoint_bsc'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='meter_register',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
